### ISSUE TITLE
Update documentation process

### ISSUE THREAD

**Issue by elseloop** [connectivedx/Phoenix#109] opened 2015-01-16 23:57 UTC
As @ajmueller notes in #108, our current documentation “is sub-optimal due to limitations of sassdoc.” We should explore some new options for generating and expanding our documentation.

**Some considerations:**

*  It would be nice to remove the Ruby dependency entirely from Phoenix, preferably using a JS-based solution we can roll into our existing build system.
*  We shouldn't give up any features in our existing documentation.
*  We should be able to include documentation inline within our partials.
*  Alongside generated styles, we should be able to include Sass and HTML for output in the documentation.

**Some candidates:**

*  [StyleDown](https://github.com/styledown/styledown): Node-based; looks for Markdown in .scss docs.
*  [StyleDocco](https://github.com/jacobrask/styledocco): Node-based; allows Markdown in inline .scss documentation for generated examples
*  [Holograms](http://trulia.github.io/hologram/): really nice and full-featured. Has a Ruby dependency, but does have a decent-looking [Gulp plugin](https://github.com/rejahrehim/gulp-hologram) available on NPM (still requires Ruby, but we could at least set up a task for it in our existing setup). Uses YAML for inline docs.
*  [Others](http://vinspee.me/style-guide-guide/)

**Comment by HugoGiraudel** [comment] 2015-01-19 20:40
> is sub-optimal due to limitations of sassdoc.

What are those limitations please @elseloop?

**Comment by ajmueller** [comment] 2015-01-19 22:39
@HugoGiraudel in looking at newer versions of sassdoc, it looks like you guys have addressed the limitations (we originally wrote the documentation over a year ago and had simply been following the original paradigm since).  We just haven't looked into a new documentation tool (or new version of sassdoc) for some time.  Some of the original limitations were:

- documenting for functions and mixins only (we worked around this by utilizing categories and "function names" when appropriate)
- no ability to output samples in markup (which appears to have been resolved by allowing [Markdown in descriptions](http://sassdoc.com/annotations/#description)?)
- a dependency on Ruby/no ability to incorporate into our Gulp build

What I loved about your system originally was JSON output, which allowed for us to parse it however we needed.  With the theming capabilities now, I think sassdoc will fit the bill perfectly.  I'll have to dig into it more, but it's looking very promising.

Thanks for checking in and if I see anything, I'll let you know!

**Comment by HugoGiraudel** [comment] 2015-01-20 08:20
@ajmueller Actually I realized after posting my comment that you were using a completely different version of SassDoc. The one you used has nothing to do with today's SassDoc whatsoever. Not the same team, not the same language, not the same features and not the same goal.

We are about to release v2 of https://github.com/sassdoc/sassdoc. Docs can be found here: https://sassdoc.com/develop/. 

Cheers.

**Comment by ajmueller** [comment] 2015-01-20 16:19
Awesome, thanks!  I saw the tweet about v2 yesterday and will definitely be checking it out.

**Comment by ajmueller** [comment] 2015-02-20 20:05
@elseloop I've started a feature branch for this work:  https://github.com/isitedesign/Phoenix/tree/feature/sassdoc-2.  So far I've only removed the references to the old Sassdoc to give us a clean slate from which to start.  Let me know if you'd like a hand in getting this started.

**Comment by ajmueller** [comment] 2015-03-12 01:23
@elseloop have you had a chance to begin any implementation of Sassdoc 2?  I'm having trouble getting it to recognize comments in files that aren't at the top of the `css` directory on a client project.  Anything contained within `functions`, `mixins`, etc. is ignored.  One thing I changed that I thought would fix it is the `paths` variable for the CSS driver.  It was `'./css/*.scss'` and I changed it to `'./css/**/*.scss'` as seen on the [Sassdoc site](http://sassdoc.com/gulp/#examples).

**Comment by HugoGiraudel** [comment] 2015-03-12 09:47
If you truly have an issue with your set up, feel free to open an issue on the official repository so we can help you.

**Comment by ajmueller** [comment] 2015-03-12 14:52
Thanks @HugoGiraudel.  I have a feeling it might be how we structure our build scripts, so I'm going to test it more before I create an issue.

One question, though:  does Sassdoc follow `@import` statements?

**Comment by HugoGiraudel** [comment] 2015-03-12 15:58
One question, though: does Sassdoc follow @import statements?

Nope. SassDoc usually runs on a folder (with optional exclude patterns).

**Comment by ajmueller** [comment] 2015-03-12 20:23
@HugoGiraudel the issue was due to me leaving in extra comments that I hadn't yet converted.  For instance:

```scss
/// Description
/// @name test
// extra comment
@function test() ...
```

If any comment is left there directly above the Sass item, no matter the content (even just a string), the annotations are ignored and not parsed into the Sassdoc generated documentation.  I can't think of an instance where this could be problematic since any comment you'd likely put there could (and should) be part of the description, but it could be seen by some as a bug since it means removing the ability to otherwise normally comment Sass code.

**Comment by HugoGiraudel** [comment] 2015-03-13 09:38
This is the expected behaviour. To put it simply, a SassDoc compliant comment has to come directly before a valid item (function, mixin, placeholder or variable). If there is anything else than empty lines between them both, the comment is simply discarded.

**Comment by ajmueller** [comment] 2015-03-13 14:19
That's what I thought, but just wanted to check.  As I mentioned, this shouldn't really be an issue.  Thanks @HugoGiraudel!

**Comment by ajmueller** [comment] 2015-03-20 23:36
Still on the to-do list:
- document `$options` maps
- clean up/provide better examples
- proofread
- theme
- better categorization of "General" (or rename others to match casing)
- define access of some functions?  Does anything other than the `number-as-words` function fit under private?

**Comment by ajmueller** [comment] 2015-04-08 18:01
Following today's tech meeting, here are some points for discussion:
- Elimination of duplicate markup in PHP templates and CSS comments used for Styledown
- Using Jade/Twig/etc. as a method of doing all of our templating as a potential means of eliminating such duplication
- Scope of Style Guide vs. Pattern Library and the audiences for each

Overall it seems that we, as an agency, have bigger discussions around our deliverables and audiences that need to happen.

**Comment by jbascue** [comment] 2015-04-08 18:34
I think it makes sense to define our intended audiences (defined by roles) which in turn will help us form a more complete problem statement to work from and help us determine the appropriate deliverable for each. 

As I see it, our audiences could generally fall into these categories and each have different needs: 

- Everyone
  - Stakeholders, creative, UX, content entry, project management, development, literally everyone involved on the project
- Experience Design 
  - front end development, creative, user experience, perhaps even content
- Development
  - Anyone involved in the implementation or development

Experience Design could perhaps be rolled into Everyone.

**Comment by kamsar** [comment] 2015-04-08 19:29
Sounds like a job for a working group @stoff :)

**Comment by ajmueller** [comment] 2015-04-08 19:59
:+1: @kamsar

Some reading that I think will help inform our decisions:
- https://medium.com/@operatino/living-style-guide-tools-in-depth-overview-28cfffb92d05
- http://alistapart.com/article/creating-style-guides
- http://24ways.org/2011/front-end-style-guides
- https://speakerdeck.com/hagenburger/style-guide-driven-development

(the last three are linked to in the first article)

**Comment by stoff** [comment] 2015-04-22 19:07
Chris Coyier recently weighed in on [Where Style Guides Fit Into Process](https://css-tricks.com/where-style-guides-fit-into-process/).  His conclusion?  "There are no answers"

**Comment by ajmueller** [comment] 2015-06-17 18:07
For the next release, 1.3.0, we will be adding Sassdoc.  Automatic Style Guide generation will be treated in a different release.

**Closed** 2015-06-19 21:04 UTC
Labels: enhancement, research
